global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'helios-gateway'
    static_configs:
      - targets: ['helios-gateway:8080']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'helios-control'
    static_configs:
      - targets: ['helios-control:8081']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'redis'
    static_configs:
      - targets: ['#redis:6379']
    metrics_path: /metrics

  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Remote write configuration (for production)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.example.com/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"
